version: '3.8'
services:
  nginx: 
    restart: always
    build: ./nginx
    ports:
      - '80:80'

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: next
      POSTGRES_PASSWORD: next
      POSTGRES_DB: next
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - "8080:8080"
    command: 
      - "-v"
      - "start-dev"
      - "--import-realm"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin 
    volumes:
      - ./keycloak:/opt/keycloak/data/import

  next-app:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      KEYCLOAK_CLIENT_ID: nextClient
      KEYCLOAK_CLIENT_SECRET: KnFnAwXuOjLiwIV9jnJC8lq6hNZrmQvg
      KEYCLOAK_ISSUER: http://localhost:8080/realms/nextRealm   # Adjust if needed
      NEXT_PUBLIC_API_URL: http://api:3001W

  
  api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://next:next@db:5432/next

